name: hello_world
description: A simple test project to verify if the orchestrator is installed correctly
author: Inmanta
author_email: code@inmanta.com
license: ASL 2.0
copyright: 2022 Inmanta
modulepath: libs
downloadpath: libs
repo:
    - type: package
      url: https://pypi.org/simple/
    - type: git
      url: https://github.com/inmanta/
install_mode: master
requires:
    - ip ~= 1.0.0
