name: quickstart
modulepath: libs
downloadpath: libs
repo: https://github.com/inmanta/
description: A quickstart project that installs a drupal website.
requires:
    - apache ~= 0.3.1
    - drupal ~= 0.7.1
    - exec ~= 1.1.0
    - ip ~= 1.0.0
    - logging ~= 0.4.1
    - mysql ~= 0.6.0
    - net ~= 0.5.0
    - php ~= 0.3
    - redhat ~= 0.8.0
    - std ~= 0.26.2
    - web ~= 0.2.2
    - yum ~= 0.5.1
