name: hello_world
description: A simple test project to verify if the orchestrator is installed correctly
author: Inmanta
author_email: code@inmanta.com
license: ASL 2.0
copyright: 2022 Inmanta
modulepath: libs
downloadpath: libs
repo:
    - type: package
      url: https://pypi.org/simple/
    - type: git
      url: https://github.com/inmanta/
install_mode: master
requires:
    - apache ~= 0.3.1
    - drupal ~= 0.7.1
    - exec ~= 1.1.0
    - ip ~= 1.0.0
    - logging ~= 0.4.1
    - mysql ~= 0.6.0
    - net ~= 0.5.0
    - php ~= 0.3
    - redhat ~= 0.8.0
    - std ~= 0.26.2
    - web ~= 0.2.2
    - yum ~= 0.5.1
